### ISSUE TITLE
Ear-Bump update needs published to QDN

### ISSUE THREAD

**Issue by QuickMythril** [Qortal/ear-bump#2]
@QortalSeth - The following pull request was approved, which greatly improves the search functionality of Ear-Bump:  https://github.com/Qortal/ear-bump/pull/1
Those changes have still not included in the application that is published to QDN.  As you are currently the only active Q-App developer, I would request that you build and publish this update as soon as possible.  Thank you.

**Comment by crowetic** [comment]
It is not solely on @QortalSeth to approve/merge code changes. I am capable of doing this in most cases as well, and where I am not (and cannot assist myself in adequately learning) I will verify with others as needed. 

I appreciate the efforts you've been making for the project overall, and will do my best to stay on top of requests, but I don't mind you bringing them up, and explaining them either. As long as there isn't any animosity with any comments, everything is fine. 

As time goes on, and things change, etc... there will be more time available and more eyes overall, and everything will start moving more quickly. Until then, things will only be able to move as fast as they can. 

Having others verify any additions, and including their commentary along with yours, may be helpful as well in certain cases. 

I will go over this shortly, and see about making myself capable of publishing updates to Ear-Bump, but I cannot guarantee it will be done immediately. 

Thank you.
